name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push: ~
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup DMD
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-2.096.0

    - name: Cache
      uses: actions/cache@v2
      with:
        path: '~/.dub'
        key: ${{ runner.os }}-test-${{ hashFiles('**/dub.json') }}
        restore-keys: ${{ runner.os }}-test-

    - name: Build library
      run: dub build

    - name: Run tests
      run: |
        dub build --build=unittest-cov --config=unittest
        ./mocked -s
        
    - name: Generate coverage report
      run: bash <(curl -s https://codecov.io/bash)

  audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup DMD
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-2.096.0

    - name: Cache
      uses: actions/cache@v2
      with:
        path: '~/.dub'
        key: ${{ runner.os }}-audit-${{ hashFiles('**/dub.json') }}
        restore-keys: ${{ runner.os }}-audit-

    - run: dub fetch dscanner --version=0.11.0
    - run: dub run dscanner -- --styleCheck source tests
