name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup DMD
      uses: WebFreak001/setup-dmd@v1
      with:
        dmd-version: 2.091.1

    - name: Run tests
      run: |
        dub build --build=unittest-cov --config=unittest
        ./mocked -s
        
    - name: Generate coverage report
      run: bash <(curl -s https://codecov.io/bash)
